services:
  postgres:
    image: postgres:16-alpine
    container_name: motherboard_systems_hq-postgres-1
    restart: always
    environment:
      POSTGRES_DB: motherboarddb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: motherboard_systems_hq-dashboard-1
    restart: always
    ports:
      - "8080:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      PORT: 3000
      POSTGRES_URL: ${POSTGRES_URL}

volumes:
  postgres_data:
